### ISSUE TITLE
Error al compilar con la Clase Cursos

### ISSUE THREAD

**Issue by VictorNievas** [jlsuarezdiaz/Parchis-IA#11]
He descargado el código y sin haber modificado nada he intentado compilarlo con make, y no me detecta la clase Cursor.
![error](https://user-images.githubusercontent.com/101177008/171141623-3ee062df-4ab6-4f17-8093-ad0df74f193e.png)
Simplemente no me detecta la clase, si me pudieran ayudar sería de gran ayuda. Gracias.

**Comment by jlsuarezdiaz** [comment]
Hola, ¿qué sistema operativo usas? ¿Y qué versión? Es posible que el gestor de paquetes no haya instalado la versión más reciente de la librería SFML (la 2.5.1) si el sistema operativo no está actualizado. Para ello puedes o actualizar el sistema operativo (por ejemplo si es Ubuntu con la 18.04 no se instala la más reciente pero con 20.04 sí se instala la buena), o si no, manteniendo el sistema operativo también sería posible instalar la versión más reciente de SFML desde el código fuente o el SDK, siguiendo estas [instrucciones](https://www.sfml-dev.org/tutorials/2.5/start-linux.php).
