### ISSUE TITLE
Segmentation fault al hacer debug

### ISSUE THREAD

**Issue by miguefeixas** [jlsuarezdiaz/Parchis-IA#12]
Hola, he intentado hacer debug usando los ficheros json que se nos proporcionan en Prado y ocurre un segmentation fault cuando se inicia el programa, concretamente en la línea 68 del archivo GUIPlayer.cpp. He probado a reemplazar mis ficheros AIPlayer.cpp y AIPlayer.h por los que se nos proporcionan al comienzo de la práctica y sigue ocurriendo lo mismo. Sin embargo, cuando inicio el programa de forma normal desde la terminal con el comando "./bin/Parchis", este funciona perfectamente.

Por si es de ayuda aquí están algunos datos de mi equipo:

- SO: Ubuntu 20.04.4 LTS
- Versión de g++: 9.4
- Versión de gdb: 9.2
- Versión de sfml: 2.5.1
- Versión de VS Code: 1.66.2

![Segmentation fault](https://user-images.githubusercontent.com/43896187/171192316-df64da90-3e16-4172-a415-238df83199ce.png)

**Comment by jlsuarezdiaz** [comment]
Hola, efectivamente a veces ocurre eso y no sabemos el porqué de momento. Parece que es por algo que introduce el debugger que hace que alguna hebra vaya más lento de lo que debería. De todas formas, de normal no te recomendamos usar el depurador porque va a ir muy lento una vez tengas la poda implementada, y cuando lo necesites usar, si lo usas en la versión sin gráfica no debería ocurrir ese error. Investigaremos esto en cualquier caso.

**Comment by miguems** [comment]
Hola!
Una solución provisional para evitar el segmentation fault es que pongas un breakpoint en la línea 68 de GUIPlayer.cpp. Al arrancar con el depurador parará en esa línea; a continuación, quita el breakpoint y dile que continúe. 
Como dice @jlsuarezdiaz  tiene pinta de ser alguna hebra (posiblemente de la parte gráfica) que tarda más de lo que debería  al iniciar el depurador y cuando la hebra principal llega a esa línea, `gui` aún no está completamente definido.

**Comment by miguefeixas** [comment]
Efectivamente, poniendo un breakpoint en esa línea funciona correctamente. Muchas gracias!
