### ISSUE TITLE
Error con la práctica 3

### ISSUE THREAD

**Issue by ChriisSimon** [jlsuarezdiaz/Parchis-IA#9]
Hola profesor, soy Cristóbal Pérez, de 2A de Informática. Le escribo para avisarle de un error en la práctica y es que he hecho la  primera parte del tutorial y el entorno gráfico no me deja empezar a jugar, sólo he llegado a la primera parte del tutorial copiando las instrucciones tal como aparecen y me da el error de que el agente se está saltando algunos turno y no sabe continuar. Le paso un comprimido con los archivos tal cuál los dejé y fotos del error. También informarle que sí he instalado la librería que hacía falta
[practica3-main.zip](https://github.com/jlsuarezdiaz/Parchis-IA/files/8761173/practica3-main.zip)
![imagen](https://user-images.githubusercontent.com/93051782/169995100-c6fae261-e29c-4b08-a828-3af15405d6e8.png)
![imagen](https://user-images.githubusercontent.com/93051782/169995357-114e6a17-6198-4985-a38d-148f66e05f83.png)

**Comment by rbnuria** [comment]
Buenas Cristóbal:

El código que veo que mandas no tiene nada del tutorial implementado. ¿Es un error al mandarlo? ¿O el problema te da nada más descargarte el código?

**Comment by ChriisSimon** [comment]
Hola profesor/a el zip que he mandado debería tener las carpetas que
aparecen cuando se descomprime el zip.
La parte del tutorial que he implementado ha sido solo la primera donde se
modifican los dos think y se hace el ./bin/Parchis --p1...

**Comment by rbnuria** [comment]
Buenas:

Sí, cuando lo abro veo las carpetas, pero no veo ninguna modificación con respecto al código que os proporcionamos.

¿Ese código, sin hacer ningún cambio, te da ese problema? ¿O es tras hacer los cambios del tutorial?

**Comment by ChriisSimon** [comment]
El problema me lo da tras hacer el primer cambio del tutorial que es crear la función think, modificarla y crear la de thinkAleatorio.
Ya que estoy quiero preguntar si puedo hacer la práctica completa en gitpod o sólo hasta el tutorial porque he vuelto a empezarla de 0, esta vez escribiendo yo el código en vez de descomentar lo que ya venía hecho pero sigue sin ir y creo que va a ser la mejor opción irse a gitpod, pero no sé si se puede hacer la práctica completamente

**Comment by jlsuarezdiaz** [comment]
Hola, ¿entonces el código inicial te funciona pero al hacer el primer cambio del tutorial no? ¿Nos puedes pasar el código **con el cambio que hayas hecho del tutorial** para ver qué puede pasar? El **código exacto con el que te ocurre el error**, el original no nos ayuda.

**Comment by jlsuarezdiaz** [comment]
En GitPod ahora mismo no es posible conectar con los ninjas pero en breve se podrá. De todas formas, nos gustaría ver primero el código para ver cuál puede ser el problema. No es normal que haya dejado de funcionar si con el código original sí funciona bien.

**Comment by ChriisSimon** [comment]
Estos son los cambios que he hecho para empezar el tutorial solo la primera parte
![imagen](https://user-images.githubusercontent.com/93051782/170833823-7505faa0-a67c-47c9-8e4e-06776da8fc6a.png)
![imagen](https://user-images.githubusercontent.com/93051782/170833835-44c42a1e-cd7b-4575-aab4-705fd5413c2c.png)
![imagen](https://user-images.githubusercontent.com/93051782/170833844-270d1dc1-40fc-4280-91cb-2df2ae13ff20.png)
Y la orden que utilizo para empezar a jugar es: ./bin/Parchis --p1 GUI 0 "Yo" --p2 AI 0 "Random"

**Comment by jlsuarezdiaz** [comment]
Buenas, ¿nos puedes mandar el proyecto completo con ese código? El proyecto tal cual te produce el error. Me lo puedes mandar por correo a jlsuarezdiaz@decsai.ugr.es

**Comment by jlsuarezdiaz** [comment]
Hola,

el problema está en que añades los atributos

```
Parchis *actual;
int jugador;
```

en la clase `AIPlayer`. Estos atributos **no hay que añadirlos**. Ya existen en la clase `Player` y son heredados en `AIPlayer`, eso es lo que se dice en el tutorial. Se puede acceder a ellos desde `AIPlayer` sin necesidad de crear ninguna variable. De hecho, al añadirlas, el juego utiliza la variable `actual` que no corresponde y de ahí los errores.

Un saludo.

**Comment by ChriisSimon** [comment]
Si Nuria, yo sólo he he hecho la primera parte del tutorial tal y como ppne
en el documento y da ese error
